### ISSUE TITLE
Create and upload binary for 0.10.0 release

### ISSUE THREAD

**Issue by etam** [golemfactory/bootstrap_go#2]
... so that we could test deployment before 0.11.0.

cc @ktomala

**Comment by etam** [comment]
Golem 0.11.0 uses messages 1.5.1. The release you've created that should be compatible with 0.11.0 is not compatible. That's why I asked to create release binaries for 0.10.0.

**Comment by etam** [comment]
Please rename the binary to bootstrap_linux_amd64

**Comment by Krigpl** [comment]
> Please rename the binary to bootstrap_linux_amd64

Done
